import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Wrapper } from "./wrapper"
import "./globals.css"
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Demystifying Server vs. Client",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-row justify-between p-8">
          <div className="flex flex-row items-center justify-start space-x-8">
            <div className="w-4 h-4 rounded-sm bg-emerald-500 mr-2" />{" "}
            <span> = Server Component</span>
            <div className="w-4 h-4 rounded-sm bg-sky-500 mr-2" />{" "}
            <span> = Client Component</span>
          </div>
          <div className="flex flex-row space-x-4">
            <Link href="/" className="underline decoration-emerald-500">
              Server Component Demo
            </Link>
            <Link href="/client" className="underline decoration-sky-500">
              Client Component Demo
            </Link>
          </div>
        </div>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  )
}
